version: '3.9'

services:
  pheme-db:
    container_name: pheme-db-container
    image: mysql:8.0.32
    restart: always
    volumes:
      - pheme:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - pheme-network
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_DB=${DATABASE_DB}

  pheme-backend:
    container_name: pheme-backend-container
    depends_on:
      pheme-db:
        condition: service_started
    volumes:
      - .:/app
    ports:
      - ${PHEME_PORT}:${PHEME_PORT}
    networks:
      - pheme-network
    pid: host
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_DB=${DATABASE_DB}
      - PHEME_HOST=${PHEME_HOST}
      - PHEME_PORT=${PHEME_PORT}
    build:
      context: ..
      dockerfile: ./ci/pheme.Dockerfile
    tty: true
    restart: on-failure

volumes:
  pheme:

networks:
  pheme-network:
    driver: bridge
